//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KinokradHD
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KinokradHDEntities : DbContext
    {
        public KinokradHDEntities()
            : base("name=KinokradHDEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Actor> Actor { get; set; }
        public virtual DbSet<Awards> Awards { get; set; }
        public virtual DbSet<Director> Director { get; set; }
        public virtual DbSet<Feedback> Feedback { get; set; }
        public virtual DbSet<Film> Film { get; set; }
        public virtual DbSet<Film_Actor> Film_Actor { get; set; }
        public virtual DbSet<Film_Director> Film_Director { get; set; }
        public virtual DbSet<Film_Genre> Film_Genre { get; set; }
        public virtual DbSet<Film_Nomination> Film_Nomination { get; set; }
        public virtual DbSet<Film_Operator> Film_Operator { get; set; }
        public virtual DbSet<Film_Screenwriter> Film_Screenwriter { get; set; }
        public virtual DbSet<Genre> Genre { get; set; }
        public virtual DbSet<Nomination> Nomination { get; set; }
        public virtual DbSet<Operator> Operator { get; set; }
        public virtual DbSet<Rating> Rating { get; set; }
        public virtual DbSet<Screenwriter> Screenwriter { get; set; }
        public virtual DbSet<Serias> Serias { get; set; }
        public virtual DbSet<Serias_Actor> Serias_Actor { get; set; }
        public virtual DbSet<Serias_Director> Serias_Director { get; set; }
        public virtual DbSet<Serias_Genre> Serias_Genre { get; set; }
        public virtual DbSet<Serias_Nominat> Serias_Nominat { get; set; }
        public virtual DbSet<Serias_Operator> Serias_Operator { get; set; }
        public virtual DbSet<Serias_Screenwriter> Serias_Screenwriter { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
