//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KinokradHD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feedback
    {
        public int ID_Feedback { get; set; }
        public Nullable<int> Score { get; set; }
        public Nullable<int> ID_User { get; set; }
        public Nullable<int> ID_Film { get; set; }
        public string Feedback1 { get; set; }
        public Nullable<int> ID_Serias { get; set; }
    
        public virtual Film Film { get; set; }
        public virtual Serias Serias { get; set; }
        public virtual User User { get; set; }
    }
}
