//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KinokradHD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Film_Screenwriter
    {
        public int ID_Film { get; set; }
        public int ID_Screenwriter { get; set; }
        public int ID { get; set; }
    
        public virtual Film Film { get; set; }
        public virtual Screenwriter Screenwriter { get; set; }
    }
}
