//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KinokradHD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Serias
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Serias()
        {
            this.Feedback = new HashSet<Feedback>();
            this.Serias_Actor = new HashSet<Serias_Actor>();
            this.Serias_Director = new HashSet<Serias_Director>();
            this.Serias_Genre = new HashSet<Serias_Genre>();
            this.Serias_Nominat = new HashSet<Serias_Nominat>();
            this.Serias_Nominat1 = new HashSet<Serias_Nominat>();
            this.Serias_Operator = new HashSet<Serias_Operator>();
            this.Serias_Screenwriter = new HashSet<Serias_Screenwriter>();
        }
    
        public int ID_Serias { get; set; }
        public string Title { get; set; }
        public string Poster { get; set; }
        public Nullable<System.DateTime> Year { get; set; }
        public Nullable<decimal> Budget { get; set; }
        public Nullable<decimal> Fees { get; set; }
        public string Country { get; set; }
        public Nullable<int> Count_episodes { get; set; }
        public Nullable<int> Duration { get; set; }
        public Nullable<int> ID_Rating { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Feedback> Feedback { get; set; }
        public virtual Rating Rating { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Serias_Actor> Serias_Actor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Serias_Director> Serias_Director { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Serias_Genre> Serias_Genre { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Serias_Nominat> Serias_Nominat { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Serias_Nominat> Serias_Nominat1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Serias_Operator> Serias_Operator { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Serias_Screenwriter> Serias_Screenwriter { get; set; }
    }
}
